# Generated by Django 3.2.5 on 2021-08-16 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_alter_subscription_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('date_of_expire', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='WeatherService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('date_of_expire', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='info',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='services',
        ),
        migrations.AddField(
            model_name='subscription',
            name='hotel_service',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscription.hotelservice'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='weather_service',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscription.weatherservice'),
        ),
    ]
