# Generated by Django 3.2.5 on 2021-08-16 18:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subscription', '0003_auto_20210816_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelservice',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weatherservice',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='hotelservice',
            unique_together={('user', 'city')},
        ),
        migrations.AlterUniqueTogether(
            name='weatherservice',
            unique_together={('user', 'city')},
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
