# Generated by Django 3.2.5 on 2021-08-26 12:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subscription', '0005_transportservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=100)),
                ('city_of_departure', models.CharField(blank=True, default=None, max_length=100)),
                ('target_city', models.CharField(max_length=100)),
                ('date_of_expire', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='transportservice',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='transportservice',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='weatherservice',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='weatherservice',
            name='user',
        ),
        migrations.DeleteModel(
            name='HotelService',
        ),
        migrations.DeleteModel(
            name='TransportService',
        ),
        migrations.DeleteModel(
            name='WeatherService',
        ),
    ]
