# Generated by Django 3.2.5 on 2021-08-26 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0006_auto_20210826_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='city_of_departure',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
