# Generated by Django 3.2.5 on 2021-08-26 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0008_alter_subscription_city_of_departure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='city_of_departure',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
