# Generated by Django 3.2.5 on 2021-08-26 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0009_alter_subscription_city_of_departure'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='subscription',
            table='Subscription',
        ),
    ]
