# Generated by Django 3.2.5 on 2021-08-26 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0010_alter_subscription_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='subscription',
            table=None,
        ),
    ]
