# Generated by Django 3.2.5 on 2021-08-07 13:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weather',
            old_name='temperature',
            new_name='current_temp',
        ),
        migrations.AddField(
            model_name='weather',
            name='current_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weather',
            name='icon',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weather',
            name='max_temp',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weather',
            name='min_temp',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='weather',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels.city'),
        ),
        migrations.AlterField(
            model_name='weather',
            name='feels_like',
            field=models.FloatField(blank=True),
        ),
    ]
