# Generated by Django 3.2.5 on 2021-08-26 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_photoforuser_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoforuser',
            name='photo',
            field=models.ImageField(max_length=150, upload_to='media/users'),
        ),
    ]
