# Generated by Django 3.2.5 on 2021-08-17 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_name', models.CharField(max_length=300)),
                ('arrival_name', models.CharField(max_length=300)),
                ('departure_date', models.DateTimeField(blank=True, null=True)),
                ('parsed_time', models.DateTimeField(blank=True, null=True)),
                ('source_name', models.CharField(max_length=350)),
                ('source_url', models.URLField(max_length=1350)),
            ],
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_name', models.CharField(blank=True, max_length=300, null=True)),
                ('train_number', models.CharField(max_length=200)),
                ('train_uid', models.CharField(max_length=200)),
                ('departure_name', models.CharField(max_length=300)),
                ('departure_code', models.IntegerField(null=True)),
                ('departure_date', models.DateTimeField(blank=True, null=True)),
                ('arrival_name', models.CharField(max_length=300)),
                ('arrival_code', models.IntegerField(null=True)),
                ('arrival_date', models.DateTimeField(blank=True, null=True)),
                ('in_route_time', models.CharField(max_length=200)),
                ('parsed_time', models.DateTimeField(blank=True, null=True)),
                ('source_name', models.CharField(max_length=350)),
                ('source_url', models.URLField(max_length=1350)),
                ('route_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.route')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_name', models.CharField(max_length=300)),
                ('departure_date', models.DateTimeField(null=True)),
                ('arrival_name', models.CharField(max_length=300)),
                ('price', models.CharField(max_length=200)),
                ('car_model', models.CharField(blank=True, max_length=200, null=True)),
                ('blablacar_url', models.URLField(max_length=350)),
                ('parsed_time', models.DateTimeField(null=True)),
                ('source_name', models.CharField(max_length=350)),
                ('source_url', models.URLField(max_length=1350)),
                ('route_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.route')),
            ],
        ),
    ]
